<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Enams\**" />
    <EmbeddedResource Remove="Enams\**" />
    <None Remove="Enams\**" />
    <Page Remove="Enams\**" />
  </ItemGroup>

</Project>
